export enum PatternType {
    AbstractFactory = "Abstract Factory",
    Adapter = "Adapter",
    Bridge = "Bridge",
    Builder = "Builder",
    ChainOfResponsibility = "Chain Of Responsibility",
    Command = "Command",
    Composite = "Composite",
    Decorator = "Decorator",
    Facade = "Facade",
    FactoryMethod = "Factory Method",
    Flyweight = "Flyweight",
    Interpreter = "Interpreter",
    Iterator = "Iterator",
    Mediator = "Mediator",
    Memento = "Memento",
    Observer = "Observer",
    Prototype = "Prototype",
    Proxy = "Proxy",
    Singleton = "Singleton",
    State = "State",
    Strategy = "Strategy",
    TemplateMethod = "Template Method",
    Visitor = "Visitor"
}